[package]
name = "zed-arkts"
version = "0.2.0"
publish = false
edition = "2021"
description = "A Zed extension for ArkTS development"
authors = ["liuyanghejerry <liuyanghejerry@126.com>"]
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
